---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeebe-chaos-test

resources:
  - zeebe.yaml
  - starter.yaml
  - worker.yaml

patchesStrategicMerge:
  - zeebe_statefulset_tolerations.yml
