apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 6
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/zeebe-io/worker:zeebe
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: "-Dapp.brokerUrl=long-running-zeebe:26500 -Dzeebe.client.requestTimeout=62000 -Dapp.worker.capacity=120 -XX:+HeapDumpOnOutOfMemoryError"
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 512Mi
