apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
  labels:
    app: starter
spec:
  selector:
    matchLabels:
      app: starter
  replicas: 1
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
      - name: starter
        image: gcr.io/zeebe-io/starter:zeebe
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: "-Dapp.brokerUrl=operate-zeebe:26500 -Dapp.starter.rate=300 -Dzeebe.client.requestTimeout=62000 -XX:+HeapDumpOnOutOfMemoryError"
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 512Mi
